export const TEMPLATES = [
  {
    id: 'midnight_pro',
    name: 'Midnight Pro',
    category: 'Tech',
    description: 'Dark elegance meets precision engineering',
    colors: { primary: '#6C63FF', bg: '#0A0A0F', accent: '#00D9FF', text: '#F0F0FF' },
    tags: ['Dark', 'Modern', 'Tech'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 50%, #6C63FF 100%)',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    category: 'Creative',
    description: 'Vibrant gradients inspired by northern lights',
    colors: { primary: '#A855F7', bg: '#0F0A1E', accent: '#06B6D4', text: '#F8F8FF' },
    tags: ['Colorful', 'Creative', 'Gradient'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #4C1D95 0%, #2563EB 50%, #06B6D4 100%)',
  },
  {
    id: 'clean_slate',
    name: 'Clean Slate',
    category: 'Corporate',
    description: 'Timeless minimalism for the corporate world',
    colors: { primary: '#1E293B', bg: '#FFFFFF', accent: '#3B82F6', text: '#1E293B' },
    tags: ['Minimal', 'White', 'ATS-Friendly'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 50%, #94A3B8 100%)',
  },
  {
    id: 'neo_tokyo',
    name: 'Neo Tokyo',
    category: 'Tech',
    description: 'Cyberpunk aesthetic for the digital age',
    colors: { primary: '#FF006E', bg: '#020010', accent: '#00FF9F', text: '#FFFFFF' },
    tags: ['Cyberpunk', 'Dark', 'Neon'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #020010 0%, #1A0030 50%, #FF006E 100%)',
  },
  {
    id: 'botanical',
    name: 'Botanical',
    category: 'Nature',
    description: 'Fresh greens for the sustainably-minded',
    colors: { primary: '#16A34A', bg: '#F0FDF4', accent: '#84CC16', text: '#14532D' },
    tags: ['Green', 'Nature', 'Clean'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 50%, #16A34A 100%)',
  },
  {
    id: 'royal_navy',
    name: 'Royal Navy',
    category: 'Finance',
    description: 'Classic authority for finance and law',
    colors: { primary: '#1E3A5F', bg: '#FAFAFA', accent: '#C9A84C', text: '#1A1A2E' },
    tags: ['Classic', 'Finance', 'Blue'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #FAFAFA 0%, #E8EEF7 50%, #1E3A5F 100%)',
  },
  {
    id: 'sunset_warm',
    name: 'Sunset Warm',
    category: 'Marketing',
    description: 'Warm and energetic for creative marketers',
    colors: { primary: '#F97316', bg: '#FFF7ED', accent: '#EC4899', text: '#1C0A00' },
    tags: ['Warm', 'Orange', 'Creative'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 50%, #F97316 100%)',
  },
  {
    id: 'mono_grid',
    name: 'Mono Grid',
    category: 'Design',
    description: 'Swiss grid perfection in black and white',
    colors: { primary: '#000000', bg: '#FFFFFF', accent: '#FF0000', text: '#000000' },
    tags: ['Minimal', 'B&W', 'Architecture'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #FFFFFF 0%, #E5E5E5 50%, #000000 100%)',
  },
  {
    id: 'neon_pulse',
    name: 'Neon Pulse',
    category: 'Gaming',
    description: 'Electric purple vibes for gamers and streamers',
    colors: { primary: '#7C3AED', bg: '#0D0014', accent: '#F0ABFC', text: '#FAF5FF' },
    tags: ['Neon', 'Purple', 'Gaming'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #0D0014 0%, #2D0057 50%, #7C3AED 100%)',
  },
  {
    id: 'paper_craft',
    name: 'Paper Craft',
    category: 'Education',
    description: 'Warm and approachable for educators',
    colors: { primary: '#78350F', bg: '#FFFBEB', accent: '#D97706', text: '#1C1400' },
    tags: ['Earthy', 'Warm', 'Education'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #FFFBEB 0%, #FEF3C7 50%, #D97706 100%)',
  },
  {
    id: 'silicon_valley',
    name: 'Silicon Valley',
    category: 'Engineering',
    description: 'Clean blue tech for engineers and developers',
    colors: { primary: '#0EA5E9', bg: '#F0F9FF', accent: '#0284C7', text: '#0C4A6E' },
    tags: ['Blue', 'Tech', 'Engineering'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #F0F9FF 0%, #E0F2FE 50%, #0EA5E9 100%)',
  },
  {
    id: 'rose_gold',
    name: 'Rose Gold',
    category: 'Fashion',
    description: 'Elegant pink gradients for creative professionals',
    colors: { primary: '#E11D48', bg: '#FFF1F2', accent: '#F43F5E', text: '#1A0010' },
    tags: ['Pink', 'Elegant', 'Fashion'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #FFF1F2 0%, #FFE4E6 50%, #E11D48 100%)',
  },
  {
    id: 'executive',
    name: 'Executive',
    category: 'Leadership',
    description: 'Premium dark blue for C-suite professionals',
    colors: { primary: '#1E3A5F', bg: '#0D1B2A', accent: '#C9A84C', text: '#F0F4FF' },
    tags: ['Dark', 'Premium', 'Executive'],
    popular: false,
    preview_gradient: 'linear-gradient(135deg, #0D1B2A 0%, #1E3A5F 50%, #C9A84C 100%)',
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    category: 'Design',
    description: 'Frosted glass UI for UX designers',
    colors: { primary: '#818CF8', bg: '#1E1B4B', accent: '#38BDF8', text: '#F0F0FF' },
    tags: ['Glass', 'Blur', 'UI/UX'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #1E1B4B 0%, #312E81 50%, #818CF8 100%)',
  },
  {
    id: 'retro_wave',
    name: 'Retro Wave',
    category: 'Arts',
    description: '80s synthwave vibes for creative artists',
    colors: { primary: '#F472B6', bg: '#1A0030', accent: '#FBBF24', text: '#FDF0FF' },
    tags: ['Retro', '80s', 'Synthwave'],
    popular: true,
    preview_gradient: 'linear-gradient(135deg, #1A0030 0%, #4A0080 50%, #F472B6 100%)',
  },
]

export const getTemplate = (id) => TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
